name: Conditions
on: [push]
jobs:
  conditions-demo:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello, world!"

      - name: trigger PROD deploy
        if: github.ref == 'refs/heads/main'
        run: echo "deploy to PROD"

      - name: tigger DEV deploy
        if: github.ref == 'refs/heads/feature-*'
        run: echo "deploy to DEV"    
